"""empty message

Revision ID: 503460424dca
Revises: 
Create Date: 2020-04-05 09:06:53.650971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503460424dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=130), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='user_unique_email'),
    sa.UniqueConstraint('username', name='user_unique_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
